server:
  port: 8756
  
spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000

riboon:
  ConnectTimeout: 100000
  ReadTimeout: 200000

zuul:
  routes:
    ms-empregado:
      service-id: ms-empregado
      path: /ms-empregado/**
      
    ms-cliente:
      service-id: ms-cliente
      path: /ms-cliente/**
      
    ms-produto:
      service-id: ms-produto
      path: /ms-produto/**
      
      