



## Porta ###
server:
 port: 8082


## H2 ##
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:ms-cliente
    username: sa
    password:
    driverClassName: org.h2.Driver

  application:
    name: ms-cliente

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      